### ISSUE TITLE
option for a transparent background

### ISSUE THREAD

**Issue by afeld** [afeld/sparkle#12]
Methinks a `background_opacity` option or something? I guess the default should be transparent, rather than white?

**Comment by sabondano** [comment]
@afeld It looks like there is an open PR for this issue so maybe we can merge and close it?

**Comment by sabondano** [comment]
Closing this issue as this feature was built and merged on https://github.com/afeld/sparkle/pull/15.

**Comment by sabondano** [comment]
@afeld should we create a new issue for adding a background_opacity option? I saw you mentioned that on this issue on Nov 15, 2015 but not sure if you think it would still be valuable to add it or if #15 met the requirement we were looking for with this issue. Just wanted to make sure you were aware as I closed this issue. Thank you!
